### ISSUE TITLE
Issue Tracking

### ISSUE THREAD

**Issue by henryjburg** [UQdeco2800/Git300x#1]
Create a section of the Git300x course describing how issues can be used to track progress in a large software project. This should include an explanation of what issues are, when they should be used, and the value they bring to a project. Information should also be provided describing how GitHub's issue tracking features can be used, including Kanban boards.

**Milestones**
- [ ]  Write and explanation of what an issue is
- [ ] Provide an example of an issue
- [ ] List steps to create an issue using GitHub
- [ ] Create a branch associated with this issue
- [ ] Add a description of how Kanban boards can be used
- [ ] Add some multiple choice questions to assess the student's knowledge

**Dependencies**
- Git200x must be completed to provide students with knowledge of branches
- The 'Git Development Workflow' section must be completed as knowledge of feature branches is required
